import "./normalize.css";
import "./globals.css";
import { mulish, josefin } from "./fonts";
import Navbar from "./components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} ${josefin.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
